const AdminActivityLog = require('../models/AdminActivityLog');
const { ensureAdmin } = require('./authController');

async function getSecurityDashboard(req, res, next) {
  try {
    if (!ensureAdmin(req, res)) return;

    // Fetch recent admin actions
    const recentActivity = await AdminActivityLog.find({})
      .sort({ createdAt: -1 })
      .limit(50);

    // Aggregate actions by admin
    const adminActionCounts = await AdminActivityLog.aggregate([
      {
        $group: {
          _id: '$adminEmail',
          count: { $sum: 1 },
          lastActive: { $max: '$createdAt' }
        }
      },
      { $sort: { count: -1 } },
      { $limit: 10 }
    ]);

    // Mock Security Events (Failed logins, IP anomalies)
    const securityEvents = [
      {
        id: 'EVT-001',
        type: 'Failed Login',
        severity: 'high',
        ip: '192.168.1.100',
        timestamp: new Date(Date.now() - 3600000),
        details: '5 failed login attempts for admin@abzora.com',
      },
      {
        id: 'EVT-002',
        type: 'New IP Access',
        severity: 'medium',
        ip: '203.0.113.42',
        timestamp: new Date(Date.now() - 86400000),
        details: 'Successful login from new IP for operations@abzora.com',
      },
      {
        id: 'EVT-003',
        type: 'Data Export',
        severity: 'low',
        ip: '192.168.1.50',
        timestamp: new Date(Date.now() - 172800000),
        details: 'Large CSV export generated by finance@abzora.com',
      }
    ];

    res.status(200).json({
      success: true,
      data: {
        recentActivity,
        adminActionCounts,
        securityEvents,
      }
    });

  } catch (error) {
    next(error);
  }
}

async function revokeAccess(req, res, next) {
  try {
    if (!ensureAdmin(req, res)) return;
    
    // In a real scenario, this would invalidate the user's session or token
    const { adminEmail } = req.body;
    
    await AdminActivityLog.create({
      adminEmail: req.user?.email || 'system@abzora.com',
      action: 'REVOKE_ACCESS',
      entityType: 'AdminUser',
      entityId: adminEmail,
      notes: `Access revoked for ${adminEmail}`,
    });

    res.status(200).json({ success: true, message: `Access revoked for ${adminEmail}` });
  } catch (error) {
    next(error);
  }
}

module.exports = {
  getSecurityDashboard,
  revokeAccess,
};
